import React, { useState } from 'react';
import { View, Text, Button, StyleSheet } from 'react-native';
import { v4 as uuidv4 } from 'uuid';
import AddTask from './AddTask';

const ToDoList = ({ tasks }) => {
  const [toDos, setToDos] = useState(tasks.map(title => ({ id: uuidv4(), title })));

  // const addCounter = (initialValue) => {  // function = (parameter) 
  //   const newCounter = { id: uuidv4(), count: initialValue };  //newVar = {the item we want to add}
  //   setCounters((prevCounters) => [...prevCounters, newCounter]);  //use the set function from the useState and add in previous to dos along with the new item with id generated by uuid4
  // };

  const addToDo = newTitle => {
    setToDos(prevToDos => [...prevToDos,{ id: uuidv4(), title: newTitle }]);
  };

  const removeToDo = id => {
    setToDos(prevToDos => prevToDos.filter(todo => todo.id !== id)); //help from stackoverflow on how to use filter https://stackoverflow.com/questions/54280241/how-to-delete-an-item-using-filter-reactjs
  };


  //pass the functions to addtask.js 
  return (
    <View style={styles.container}>
      {toDos.map(({ id, title }) => ( //map thing is kinda like a for loop
        <View key={id} style={styles.itemContainer}>
          <Text>{title}</Text>
          <Button onPress={() => removeToDo(id)} title="Remove" />
        </View>
      ))}
      <AddTask onAddTask={addToDo} />
    </View>
  );
};

ToDoList.defaultProps = {
  tasks: []
};

const styles = StyleSheet.create({
  todoListContainer: {
    margin: 10,
  },
  todoItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    marginVertical: 5,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 5,
  },
});

export default ToDoList;
